### ISSUE TITLE
No libraries found (Lame MP3, ffmpeg) after the last update

### ISSUE THREAD

**Issue by bassterror** [linuxserver/docker-audacity#5]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Import/Export should be working with external libraries (FFmpeg and LAME MP3).

## Current Behavior

When you try to import audio from a video file (in my case .mkv) it throws the following error: "Audacity did not recognize the type of the file 'foo.mkv'. Try installing FFmpeg."

## Steps to Reproduce

1. File -> Import -> Audio -> Open
2. Throws the error mentioned above
3. Edit -> Preferences -> Libraries
4. No libraries detected (I don't know how to find them. Before the last update everything was working without additional setup/adjustments.)

## Environment
**OS:** DSM 6.2.4-25556 (Synology DS918+)
**CPU architecture:** Linux x86_64
**How docker service was installed:** From the official Docker repo.

## Command used to create docker container (run/create/compose/screenshot)

![Screenshot (18)](https://user-images.githubusercontent.com/4514140/133665430-6f17f788-53bf-470a-8825-92ceb0ed6e0e.png)

## Docker logs

[_Audacity_logs.txt](https://github.com/linuxserver/docker-audacity/files/7180130/_Audacity_logs.txt)

**Comment by aptalca** [comment]
Thanks for the report. The latest version uses their appimage releases. I assumed it contained everything necessary but maybe it relies on external libraries? Their docs range from awful to non-existent.

Can you exec into the container with `docker exec -it audacity bash` and then install ffmpeg with the following?
```
apt update && apt install ffmpeg
```
then restart the container and see if it works?

Thanks

**Comment by bassterror** [comment]
This resolved only LAME mp3. How weird is that? LOL
![Screenshot](https://user-images.githubusercontent.com/4514140/133676427-5c2d37ba-9f75-445b-b9fc-786b5a5aac6e.png)

I run it for a second time and this is the result.
![Screenshot](https://user-images.githubusercontent.com/4514140/133676105-2f03483e-9dc2-4116-b731-35f51699f56e.png)

**Comment by aptalca** [comment]
It seems the appimage version wants `libavformat.so.55` which is super old and is not available in the last two LTS releases of ubuntu (bionic and focal). They have versions 57 and 58 respectively.

**Comment by aptalca** [comment]
upstream issue: https://github.com/audacity/audacity/pull/1623

you can switch back to the previous version until then

**Comment by bassterror** [comment]
Yes, everything is working fine with the previous version. It seems we'll wait a bit until the next version. Thank you for your help!
